// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Artist struct {
	ID    int32  `json:"id"`
	Group string `json:"group"`
}

type Library struct {
	ID          int32     `json:"id"`
	GroupID     int32     `json:"group_id"`
	Song        string    `json:"song"`
	ReleaseDate time.Time `json:"releaseDate"`
	Text        string    `json:"text"`
	Link        string    `json:"link"`
}
