// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Library struct {
	ID          int32       `json:"id"`
	Group       string      `json:"group"`
	Song        string      `json:"song"`
	ReleaseDate pgtype.Date `json:"releaseDate"`
	Text        pgtype.Text `json:"text"`
	Patronymic  pgtype.Text `json:"patronymic"`
}
